pipeline { 

    environment { 

        registry = "than97/pvpkg" 

        registryCredential = '85454c7d-a176-4e4c-94c2-d415e42a4cc3' 

        dockerImage = '' 
    }
    agent any 

    stages { 


        stage('Building our image') { 

            steps { 

                script { 
                  dir("${env.WORKSPACE}/ubuntu/18.04") {
                  sh "pwd"

                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                }
               }
            } 

        }

        stage('Deploy our image') { 

            steps { 

                script { 
                   
      
                    docker.withRegistry( '', registryCredential ) { 

                        dockerImage.push() 
                    }

                } 

            }

        } 
        stage('Cleaning up') { 

            steps { 

                sh "docker rmi $registry:$BUILD_NUMBER" 

            }
        } 
    }
}

