ARG OS_VER=8
FROM oraclelinux:$OS_VER

ARG DOCKER_USER=docker
ARG UHD_BRANCH=master
ARG GRC_BRANCH=maint-3.10

RUN yum update --refresh && yum install -y dnf-plugins-core oracle-epel-release-el8
RUN dnf config-manager --set-enabled ol8_codeready_builder
RUN yum install -y sudo make cmake git rpm-build rpmdevtools vim wget xorg-x11-xauth xorg-x11-apps gcc-toolset-13 lftp curl jq

RUN git clone https://github.com/ncopa/su-exec.git  /usr/src/su-exec
WORKDIR /usr/src/su-exec
RUN source /opt/rh/gcc-toolset-13/enable && make && install -m 0755 su-exec /usr/bin/

RUN groupadd "$DOCKER_USER" && \
    groupadd sudo && \
    useradd -ms /bin/bash -g $DOCKER_USER -G sudo $DOCKER_USER && \
    echo "${DOCKER_USER}:${DOCKER_USER}" | chpasswd  && \
    echo "$DOCKER_USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers 

RUN dnf copr enable -y pervices/develop && \
    dnf copr enable -y pervices/release && \
    dnf copr enable -y pervices/tools && yum update --refresh

USER $DOCKER_USER
WORKDIR /home/$DOCKER_USER

ARG GRC=false
# Installing GNU Radio and test dependencies based on the GRC flag
RUN if [ "$GRC" = "true" ]; then \
        sudo yum install -y gnuradiopv && \
        sudo yum install -y python3.11-pip && \
        sudo alternatives --set python3 /usr/bin/python3.11 && \
        sudo pip-3.11 install reportlab retrying matplotlib ; \
    fi

ARG PKG=base
# Building or downloading UHD based on the PKG flag
RUN if [ "$PKG" = "internal" ]; then \
        wget https://raw.githubusercontent.com/pervices/uhd/master/host/cmake/rpm-pv/libuhdpv.spec && \
        sudo dnf builddep -y libuhdpv.spec && \
        git clone -b $UHD_BRANCH https://github.com/pervices/uhd.git && \
        mkdir -p uhd/host/build && cd uhd/host/build && \
        source /opt/rh/gcc-toolset-13/enable && \
        cmake -DCMAKE_INSTALL_PREFIX="/usr" \
              -DPKG_LIB_DIR="/usr/lib/uhd" \
              -DENABLE_CRIMSON_TNG="ON" \
              -DENABLE_CYAN_4R4T="ON" \
              -DENABLE_CYAN_8R="ON" \
              -DENABLE_CYAN_16T="ON" \
              -DENABLE_CYAN_64T="OFF" \
              -DENABLE_CYAN_P1HDR16T="ON" \
              -DENABLE_CYAN_P1HDR32T="ON" \
              -DENABLE_N300="OFF" \
              -DENABLE_E320="OFF" \
              -DENABLE_USRP1="OFF" \
              -DENABLE_USRP2="ON" \
              -DENABLE_B200="OFF" \
              -DENABLE_B100="OFF" \
              -DENABLE_X300="OFF" \
              -DENABLE_OCTOCLOCK="OFF" \
              -DENABLE_DOXYGEN="OFF" \
              -DENABLE_USB="OFF" \
              -DENABLE_TESTS="OFF" \
              -DENABLE_EXAMPLES="ON" \
              -DENABLE_UTILS="ON" \  
              -DENABLE_DPDK="OFF" \     
              -DPYTHON_EXECUTABLE=/usr/bin/python3.11 \
              .. && \
        make -j$(nproc) && sudo make install ; \
    elif [ "$PKG" = "release" ]; then \
        sudo yum install -y libuhdpv ; \
    elif [ "$PKG" = "nightly" ]; then \
        if [ "$GRC" = "true" ]; then \
            sudo yum remove -y libuhdpv && \
            sudo yum install -y libuhdpv-nightly gnuradiopv; \
        else \
            sudo yum install -y libuhdpv-nightly ; \
        fi \
    elif [ "$PKG" = "base" ]; then \
        echo "Building base image.." ; \
    else \
        exit 1 ; \
    fi

# Finishing up
WORKDIR /home/$DOCKER_USER
COPY SimpleShipTest.grc SimpleShipTest.grc
RUN rm -rf uhd && touch .Xauthority
USER root
COPY rev-dkr /usr/local/sbin/
COPY entrypoint /
RUN chmod 0755 /entrypoint && \
    sed "s/\$DOCKER_USER/$DOCKER_USER/g" -i /entrypoint
ENTRYPOINT ["/entrypoint"]
