# These settings override the ones in /etc/security/limits.conf file
# For more information, see limits.conf(5)

# Set the nice priority limit to maximum so UHD has permission to prioritize threads
1000:            -       nice            -20

# Set the memlock limit high enough so processes can use all hugepages for memlock operations.
# To use all hugepages, the value should be ``number of hugepages * size of hugepages``.
# Number of hugepages is set with the``vm.nr_hugepages`` system conf setting. The size of hugepages can be checked with ``cat /proc/meminfo | grep HugePagesize
# The default value used here assumes 8192 hugepages that are 2048kB. Note the units used to set the limit are in kB.
1000:            -       memlock         16777216
