# This limits the number of processes per user as a mitigation
# against some, but not all, forms of accidental forkbombs.
# This limit has been deliberately specified to be 
# substantially higher than that required to prevent 
# bash-like fork bombs, as the anticipated HPC use case 
# means that a reasonable software deployments may require
# spawning a large number of processes.
#
# If your use case or applications do not require this, you
# can lower this to 512 or 1024 to provide additional 
# protection.

@users  soft    nproc   32767
@users  hard    nproc   65535
