Document: uhdpv
Title: Debian uhdpv Manual
Author: <insert document author here>
Abstract: This manual describes what uhdpv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/uhdpv/uhdpv.sgml.gz

Format: postscript
Files: /usr/share/doc/uhdpv/uhdpv.ps.gz

Format: text
Files: /usr/share/doc/uhdpv/uhdpv.text.gz

Format: HTML
Index: /usr/share/doc/uhdpv/html/index.html
Files: /usr/share/doc/uhdpv/html/*.html
